version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springbootapp
    ports:
      - "8080:8080"
    networks:
      - app_network
    environment:
      - SPRING_PROFILES_ACTIVE=local

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
    networks:
      - app_network
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

networks:
  app_network:
