name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'production'
        options:
          - production

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: production
