name: Java CI with Maven and Docker

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml -Dspring.config.additional-location=file:./src/main/resources/bootstrap-ci.yml
        env:
          SPRING_PROFILES_ACTIVE: ci

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: montassarjalloul
          password: dckr_pat_T-R6Mhh1lBk18vpU5BROmyFAUhM

      - name: Build and Push Docker Image (Staging)
        if: ${{ inputs.environment == 'staging' }}
        run: |
          docker build -t montassarjalloul/mrcsurvey:latest .
          docker push montassarjalloul/mrcsurvey:latest
      #To be changed later
      - name: Build and Push Docker Image (Production)
        if: ${{ inputs.environment == 'production' }}
        run: |
          docker build -t montassarjalloul/mrcsurvey:latest .
          docker push montassarjalloul/mrcsurvey:latest

      - name: Trigger Render Deploy (Staging)
        if: ${{ inputs.environment == 'staging' }}
        run: curl -X POST https://api.render.com/deploy/srv-cq6mbvqju9rs73eb6c9g?key=aAXtEIvXc1o
      #To be changed later
      - name: Trigger Render Deploy (Production)
        if: ${{ inputs.environment == 'production' }}
        run: curl -X POST https://api.render.com/deploy/srv-cq6mbvqju9rs73eb6c9g?key=aAXtEIvXc1o
