name: Java CI with Maven and Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml -Dspring.config.additional-location=file:./src/main/resources/bootstrap-ci.yml
        env:
          SPRING_PROFILES_ACTIVE: ci

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: montassarjalloul
          password: dckr_pat_T-R6Mhh1lBk18vpU5BROmyFAUhM

      - name: Build and Push Docker Image
        run: |
          docker build -t montassarjalloul/mrcsurvey:latest .
          docker push montassarjalloul/mrcsurvey:latest

      - name: Install Scalingo CLI
        run: |
          curl -O https://cli-dl.scalingo.io/install && bash install
          export PATH=$PATH:/usr/local/bin

      - name: Log in to Scalingo
        run: scalingo login --api-token tk-us-1x_HVTg3tFHnF6xWQ6UfSK_tJ0WlX5IvshyUqflMsxBMMO5u

      - name: Deploy to Scalingo
        run: |
          scalingo --app mrcsurvey env-set DOCKER_IMAGE=mrsurvey:latest
          scalingo --app mrcsurvey deploy docker montassarjalloul/mrcsurvey:latest
