name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Import Secrets from Vault
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: https://my-vault-app-f93d58bccb0a.herokuapp.com
          token: hvs.CAESIH_7Pz78iq5WeFKFPVdKkwznjB2MCpAdiMHRtQQvBgX2Gh4KHGh2cy5iUndjWVROYjh1Z05MYkVoT2xQWlFIVUo
          secrets: |
            v1/mysql/data/database host | DB_HOST ;
            v1/mysql/data/database jwt_secret | JWT_SECRET ;
            v1/mysql/data/database password | DB_PASSWORD ;
            v1/mysql/data/database port | DB_PORT ;
            v1/mysql/data/database username | DB_USERNAME

      - name: Validate URI
        run: |
          echo "Validating URI..."
          printf '%s\n' "SPRING_CLOUD_VAULT_URI=${{ env.SPRING_CLOUD_VAULT_URI }}" | cat -v
          if [[ ! "${{ env.SPRING_CLOUD_VAULT_URI }}" =~ ^https:// ]]; then
            echo "Invalid URI: ${{ env.SPRING_CLOUD_VAULT_URI }}"
            exit 1
          fi

      - name: Print and Validate Fetched Secrets
        run: |
          echo "Validating fetched secrets..."
          echo "DB_HOST=${{ env.DB_HOST }}"
          echo "JWT_SECRET=${{ env.JWT_SECRET }}"
          echo "DB_PASSWORD=${{ env.DB_PASSWORD }}"
          echo "DB_PORT=${{ env.DB_PORT }}"
          echo "DB_USERNAME=${{ env.DB_USERNAME }}"

          if [[ -z "${{ env.DB_HOST }}" || -z "${{ env.JWT_SECRET }}" || -z "${{ env.DB_PASSWORD }}" || -z "${{ env.DB_PORT }}" || -z "${{ env.DB_USERNAME }}" ]]; then
            echo "One or more secrets are missing. Validation failed."
            exit 1
          fi

      - name: Build with Maven
        run: mvn -B package --file pom.xml
        env:
          DB_HOST: ${{ env.DB_HOST }}
          JWT_SECRET: ${{ env.JWT_SECRET }}
          DB_PASSWORD: ${{ env.DB_PASSWORD }}
          DB_PORT: ${{ env.DB_PORT }}
          DB_USERNAME: ${{ env.DB_USERNAME }}

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
