name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_DATABASE: un0gn58m9mjrc2vw
          MYSQL_USER: rks2o6t3e2zyd131
          MYSQL_ROOT_PASSWORD: iggw8tiy1vlwu3ss
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Wait for MySQL to be ready
        run: |
          while ! mysqladmin ping -h"i943okdfa47xqzpy.cbetxkdyhwsb.us-east-1.rds.amazonaws.com" --silent; do
            echo "Waiting for MySQL to be ready..."
            sleep 2
          done

      - name: Set Environment Variables for Vault and MySQL
        run: |
          echo "SPRING_PROFILES_ACTIVE=ci" >> $GITHUB_ENV
          echo "SPRING_CLOUD_VAULT_URI=https://my-vault-app-f93d58bccb0a.herokuapp.com" >> $GITHUB_ENV
          echo "SPRING_CLOUD_VAULT_TOKEN=hvs.CAESIH_7Pz78iq5WeFKFPVdKkwznjB2MCpAdiMHRtQQvBgX2Gh4KHGh2cy5iUndjWVROYjh1Z05MYkVoT2xQWlFIVUo" >> $GITHUB_ENV

          # MySQL connection details
          echo "DB_HOST=i943okdfa47xqzpy.cbetxkdyhwsb.us-east-1.rds.amazonaws.com" >> $GITHUB_ENV
          echo "DB_PORT=3306" >> $GITHUB_ENV
          echo "DB_NAME=un0gn58m9mjrc2vw" >> $GITHUB_ENV
          echo "DB_USERNAME=rks2o6t3e2zyd131" >> $GITHUB_ENV
          echo "MYSQL_ROOT_PASSWORD=iggw8tiy1vlwu3ss" >> $GITHUB_ENV

      - name: Run Maven tests
        run: mvn test
        env:
          SPRING_PROFILES_ACTIVE: ci
          SPRING_CLOUD_VAULT_URI: ${{ env.SPRING_CLOUD_VAULT_URI }}
          SPRING_CLOUD_VAULT_TOKEN: ${{ env.SPRING_CLOUD_VAULT_TOKEN }}
          DB_HOST: ${{ env.DB_HOST }}
          DB_PORT: ${{ env.DB_PORT }}
          DB_NAME: ${{ env.DB_NAME }}
          DB_USERNAME: ${{ env.DB_USERNAME }}
          MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_ROOT_PASSWORD }}

      - name: Build with Maven
        run: mvn -B package --file pom.xml
        env:
          SPRING_PROFILES_ACTIVE: ci
          SPRING_CLOUD_VAULT_URI: ${{ env.SPRING_CLOUD_VAULT_URI }}
          SPRING_CLOUD_VAULT_TOKEN: ${{ env.SPRING_CLOUD_VAULT_TOKEN }}
          DB_HOST: ${{ env.DB_HOST }}
          DB_PORT: ${{ env.DB_PORT }}
          DB_NAME: ${{ env.DB_NAME }}
          DB_USERNAME: ${{ env.DB_USERNAME }}
          MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_ROOT_PASSWORD }}

      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
