name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Authenticate with Vault and fetch secrets
      id: vault
      run: |
        # Authenticate with Vault (Example using GitHub OIDC)
        VAULT_ROLE="github-actions"
        VAULT_URL="https://my-vault-app-f93d58bccb0a.herokuapp.com"

        JWT=$(curl -s --request POST --url "https://api.github.com/actions/jobs/${{ github.run_id }}/oidc-token" --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" | jq -r .value)
        
        VAULT_TOKEN=$(curl -s --request POST --data '{"jwt": "'$JWT'", "role": "'$VAULT_ROLE'"}' $VAULT_URL/v1/auth/github/login | jq -r .auth.client_token)
        
        echo "VAULT_TOKEN=$VAULT_TOKEN" >> $GITHUB_ENV
        
        # Fetch the secrets from Vault
        DB_URL=$(curl -s --header "X-Vault-Token: $VAULT_TOKEN" $VAULT_URL/v1/mysql/data/database | jq -r .data.data.url)
        DB_USERNAME=$(curl -s --header "X-Vault-Token: $VAULT_TOKEN" $VAULT_URL/v1/mysql/data/database | jq -r .data.data.username)
        DB_PASSWORD=$(curl -s --header "X-Vault-Token: $VAULT_TOKEN" $VAULT_URL/v1/mysql/data/database | jq -r .data.data.password)

        echo "DB_URL=$DB_URL" >> $GITHUB_ENV
        echo "DB_USERNAME=$DB_USERNAME" >> $GITHUB_ENV
        echo "DB_PASSWORD=$DB_PASSWORD" >> $GITHUB_ENV

    - name: Build with Maven
      run: mvn -B package --file pom.xml
      env:
        DB_URL: ${{ env.DB_URL }}
        DB_USERNAME: ${{ env.DB_USERNAME }}
        DB_PASSWORD: ${{ env.DB_PASSWORD }}

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
