name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Set Vault Token and URI
      run: |
        echo "SPRING_CLOUD_VAULT_URI=https://my-vault-app-f93d58bccb0a.herokuapp.com" >> $GITHUB_ENV
        echo "SPRING_CLOUD_VAULT_TOKEN=hvs.CAESIH_7Pz78iq5WeFKFPVdKkwznjB2MCpAdiMHRtQQvBgX2Gh4KHGh2cy5iUndjWVROYjh1Z05MYkVoT2xQWlFIVUo" >> $GITHUB_ENV

    - name: Fetch secrets from Vault
      id: vault
      run: |
        VAULT_URL="https://my-vault-app-f93d58bccb0a.herokuapp.com"
        VAULT_TOKEN="hvs.CAESIH_7Pz78iq5WeFKFPVdKkwznjB2MCpAdiMHRtQQvBgX2Gh4KHGh2cy5iUndjWVROYjh1Z05MYkVoT2xQWlFIVUo"

        # Fetch the secrets from Vault
        DB_URL=$(curl -s --header "X-Vault-Token: $VAULT_TOKEN" $VAULT_URL/v1/mysql/data/database | jq -r .data.data.url)
        DB_USERNAME=$(curl -s --header "X-Vault-Token: $VAULT_TOKEN" $VAULT_URL/v1/mysql/data/database | jq -r .data.data.username)
        DB_PASSWORD=$(curl -s --header "X-Vault-Token: $VAULT_TOKEN" $VAULT_URL/v1/mysql/data/database | jq -r .data.data.password)

        echo "DB_URL=$DB_URL" >> $GITHUB_ENV
        echo "DB_USERNAME=$DB_USERNAME" >> $GITHUB_ENV
        echo "DB_PASSWORD=$DB_PASSWORD" >> $GITHUB_ENV

    - name: Build with Maven
      run: mvn -B package --file pom.xml
      env:
        SPRING_CLOUD_VAULT_URI: ${{ env.SPRING_CLOUD_VAULT_URI }}
        SPRING_CLOUD_VAULT_TOKEN: ${{ env.SPRING_CLOUD_VAULT_TOKEN }}
        DB_URL: ${{ env.DB_URL }}
        DB_USERNAME: ${{ env.DB_USERNAME }}
        DB_PASSWORD: ${{ env.DB_PASSWORD }}

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
